DROP TABLE EMPAUTHORIZATION;
DROP TABLE SALES_MESSAGE;
DROP TABLE EMPRIGHT;
DROP TABLE NEWS;
DROP TABLE FAQ;
DROP TABLE PLANEHOTELDETAIL;
DROP TABLE PLANEHOTELORDER;
DROP TABLE PLANEHOTEL;
DROP TABLE PURCHASEORDER;
DROP TABLE PURCHASEREPORT;
DROP TABLE PURCHASE;
DROP TABLE ACCOUNTRECORD;
DROP TABLE TRIPDETAIL;
DROP TABLE TRIPORDER;
DROP TABLE TRIP;
DROP TABLE RECOMMENDTRIPDETAIL;
DROP TABLE RECOMMENDTRIP;
DROP TABLE SPOT;
DROP TABLE PACORDER;
DROP TABLE PACTRIPCONTENT;
DROP TABLE PACKAGE;
DROP TABLE MEMBERPRIVATEMESSAGE;
DROP TABLE BLOGPOSTREPORT;
DROP TABLE BLOGPOSTCOMMENT;
DROP TABLE BLOGPOST;
DROP TABLE BLOGPOSTTAG;
DROP TABLE NOTIFICATION;
DROP TABLE MEMAUTH;
DROP TABLE MEMRIGHT;
DROP TABLE MEMBER;
DROP TABLE EMPLOYEE;

DROP SEQUENCE NEWS_SEQ;
DROP SEQUENCE FAQ_SEQ;
DROP SEQUENCE PHO_SEQ;
DROP SEQUENCE PH_SEQ;
DROP SEQUENCE PORID_SEQ;
DROP SEQUENCE PREID_SEQ;
DROP SEQUENCE PURID_SEQ;
DROP SEQUENCE ACRID_SEQ;
DROP SEQUENCE TDE_SEQ;
DROP SEQUENCE TOD_SEQ;
DROP SEQUENCE TRI_SEQ;
DROP SEQUENCE RTD_SEQ;
DROP SEQUENCE RTR_SEQ;
DROP SEQUENCE SPO_SEQ;
DROP SEQUENCE PCD_SEQ;
DROP SEQUENCE PACTR_SEQ;
DROP SEQUENCE PAC_SEQ;
DROP SEQUENCE MPM_SEQ;
DROP SEQUENCE BPR_SEQ;
DROP SEQUENCE BPC_SEQ;
DROP SEQUENCE POS_SEQ;
DROP SEQUENCE TAG_SEQ;
DROP SEQUENCE NOT_SEQ;
DROP SEQUENCE MER_SEQ;
DROP SEQUENCE MEM_SEQ;
DROP SEQUENCE SEQ_EMP_EMPNO;
DROP SEQUENCE SEQ_EMR_EMRNO;
DROP SEQUENCE SEQ_SME_SMENO;

-----------------------建立會員表格-----------------------

CREATE TABLE MEMBER (
    MEMNO VARCHAR2(9) PRIMARY KEY NOT NULL,
    MEMACC VARCHAR2(24) NOT NULL,
    MEMPWD VARCHAR2(24) NOT NULL,
    MEMEMAIL VARCHAR2(320) NOT NULL,
    MEMEMAILVALID NUMBER(1) NOT NULL,
    MEMREALNAME VARCHAR2(20) NOT NULL,
    MEMENGNAME VARCHAR2(100),
    MEMPHONE NUMBER(9),
    MEMBIRTH DATE,
    MEMADDR VARCHAR(200),
    MEMIDNO VARCHAR(10),
    MEMBANKACC VARCHAR2(20),
    MEMPHOTO BLOB
);
CREATE SEQUENCE MEM_SEQ
    START WITH 1
    INCREMENT BY 1;
INSERT INTO MEMBER (MEMNO, MEMACC, MEMPWD, MEMEMAIL, MEMEMAILVALID, MEMREALNAME) 
    VALUES (('MEM' || LPAD(to_char(MEM_SEQ.NEXTVAL), 6 , '0')), 'ALICE', 123456, 'alice@abc.com', 1, '愛麗絲');
INSERT INTO MEMBER (MEMNO, MEMACC, MEMPWD, MEMEMAIL, MEMEMAILVALID, MEMREALNAME) 
    VALUES (('MEM' || LPAD(to_char(MEM_SEQ.NEXTVAL), 6 , '0')), 'BOB', 123456, 'bob@abc.com', 1, '鮑伯');
INSERT INTO MEMBER (MEMNO, MEMACC, MEMPWD, MEMEMAIL, MEMEMAILVALID, MEMREALNAME) 
    VALUES (('MEM' || LPAD(to_char(MEM_SEQ.NEXTVAL), 6 , '0')), 'CHARLIE', 123456, 'charlie@abc.com', 1, '查理');

-----------------------建立會員訊息表格-----------------------

CREATE TABLE MEMBERPRIVATEMESSAGE (
    MPMNO VARCHAR2(9) PRIMARY KEY NOT NULL,
    MPMSENDER VARCHAR2(9) REFERENCES MEMBER(MEMNO) NOT NULL,
    MPMRECIVER VARCHAR2(9) REFERENCES MEMBER(MEMNO) NOT NULL,
    MPMTITLE VARCHAR2(127),
    MPMCONTENT VARCHAR2(255),
    MPMTIME TIMESTAMP,
    MPMREADED NUMBER(1)
);
CREATE SEQUENCE MPM_SEQ
    START WITH 1
    INCREMENT BY 1;
INSERT INTO MEMBERPRIVATEMESSAGE (MPMNO, MPMSENDER, MPMRECIVER, MPMTITLE, MPMCONTENT, MPMTIME, MPMREADED) 
    VALUES (('MPM' || LPAD(to_char(MPM_SEQ.NEXTVAL), 6 , '0')), 'MEM000001', 'MEM000002', '系統測試', '愛麗絲給鮑伯的簡訊', SYSTIMESTAMP, 0);
INSERT INTO MEMBERPRIVATEMESSAGE (MPMNO, MPMSENDER, MPMRECIVER, MPMTITLE, MPMCONTENT, MPMTIME, MPMREADED) 
    VALUES (('MPM' || LPAD(to_char(MPM_SEQ.NEXTVAL), 6 , '0')), 'MEM000002', 'MEM000001', '系統測試2', '鮑伯回給愛麗絲', SYSTIMESTAMP, 0);
INSERT INTO MEMBERPRIVATEMESSAGE (MPMNO, MPMSENDER, MPMRECIVER, MPMTITLE, MPMCONTENT, MPMTIME, MPMREADED) 
    VALUES (('MPM' || LPAD(to_char(MPM_SEQ.NEXTVAL), 6 , '0')), 'MEM000001', 'MEM000003', '系統廣播', '愛麗絲給查理的簡訊', SYSTIMESTAMP, 0);

-----------------------建立旅人文章分類標籤表格-----------------------

CREATE TABLE BLOGPOSTTAG (
    TAGNO VARCHAR2(9) PRIMARY KEY NOT NULL,
    TAGCONTENT VARCHAR(20)
);
INSERT INTO BLOGPOSTTAG VALUES (1, '傻眼');
INSERT INTO BLOGPOSTTAG VALUES (2, '新奇');
INSERT INTO BLOGPOSTTAG VALUES (3, '搞笑');
CREATE SEQUENCE TAG_SEQ
    START WITH 1
    INCREMENT BY 1;
INSERT INTO BLOGPOSTTAG (TAGNO, TAGCONTENT) VALUES (('TAG' || LPAD(to_char(TAG_SEQ.NEXTVAL), 6 , '0')), '傻眼');
INSERT INTO BLOGPOSTTAG (TAGNO, TAGCONTENT) VALUES (('TAG' || LPAD(to_char(TAG_SEQ.NEXTVAL), 6 , '0')), '新奇');
INSERT INTO BLOGPOSTTAG (TAGNO, TAGCONTENT) VALUES (('TAG' || LPAD(to_char(TAG_SEQ.NEXTVAL), 6 , '0')), '搞笑');

-----------------------建立旅人文章表格-----------------------

CREATE TABLE BLOGPOST (
    POSNO VARCHAR2(9) PRIMARY KEY NOT NULL,
    MEMNO VARCHAR2(9) REFERENCES MEMBER(MEMNO) NOT NULL,
    TAGNO VARCHAR2(9) REFERENCES BLOGPOSTTAG(TAGNO) NOT NULL,
    POSTITLE VARCHAR2(127) NOT NULL,
    POSCONTENT CLOB NOT NULL,
    POSTIME TIMESTAMP
);
CREATE SEQUENCE POS_SEQ
    START WITH 1
    INCREMENT BY 1;
INSERT INTO BLOGPOST (POSNO, MEMNO, TAGNO, POSTITLE, POSCONTENT, POSTIME)
    VALUES (('POS' || LPAD(to_char(POS_SEQ.NEXTVAL), 6 , '0')), 'MEM000001', 1, '超傻眼喵喵', '喵電感應', SYSTIMESTAMP);
INSERT INTO BLOGPOST (POSNO, MEMNO, TAGNO, POSTITLE, POSCONTENT, POSTIME)
    VALUES (('POS' || LPAD(to_char(POS_SEQ.NEXTVAL), 6 , '0')), 'MEM000002', 2, '美秀集團', '王電火遇到電火王', SYSTIMESTAMP);
INSERT INTO BLOGPOST (POSNO, MEMNO, TAGNO, POSTITLE, POSCONTENT, POSTIME)
    VALUES (('POS' || LPAD(to_char(POS_SEQ.NEXTVAL), 6 , '0')), 'MEM000003', 3, '濁水溪公社', '卡通手槍', SYSTIMESTAMP);

-----------------------建立文章留言表格-----------------------

CREATE TABLE BLOGPOSTCOMMENT (
    BPCNO VARCHAR2(9) PRIMARY KEY NOT NULL,
    MEMNO VARCHAR2(9) REFERENCES MEMBER(MEMNO) NOT NULL,
    POSNO VARCHAR2(9) REFERENCES BLOGPOST(POSNO) NOT NULL,
    BPCCONTENT CLOB NOT NULL,
    BPCTIME TIMESTAMP
);
CREATE SEQUENCE BPC_SEQ
    START WITH 1
    INCREMENT BY 1;
INSERT INTO BLOGPOSTCOMMENT (BPCNO, MEMNO, POSNO, BPCCONTENT, BPCTIME)
    VALUES (('BPC' || LPAD(to_char(BPC_SEQ.NEXTVAL), 6 , '0')), 'MEM000001', 'POS000001', '姆咪姆咪心動動', SYSTIMESTAMP);
INSERT INTO BLOGPOSTCOMMENT (BPCNO, MEMNO, POSNO, BPCCONTENT, BPCTIME)
    VALUES (('BPC' || LPAD(to_char(BPC_SEQ.NEXTVAL), 6 , '0')), 'MEM000002', 'POS000001', '姆咪姆咪蹦蹦跳', SYSTIMESTAMP);
INSERT INTO BLOGPOSTCOMMENT (BPCNO, MEMNO, POSNO, BPCCONTENT, BPCTIME)
    VALUES (('BPC' || LPAD(to_char(BPC_SEQ.NEXTVAL), 6 , '0')), 'MEM000003', 'POS000001', '完美姆咪世界', SYSTIMESTAMP);

-----------------------建立系統通知表格-----------------------

CREATE TABLE NOTIFICATION (
    NOTNO VARCHAR2(9) PRIMARY KEY NOT NULL,
    MEMNO VARCHAR2(9) REFERENCES MEMBER(MEMNO) NOT NULL,
    NOTCONTENT VARCHAR(255) NOT NULL,
    NOTREADED NUMBER(1),
    NOTTIME TIMESTAMP
);
CREATE SEQUENCE NOT_SEQ
    START WITH 1
    INCREMENT BY 1;

-----------------------建立權限功能表格-----------------------

CREATE TABLE MEMRIGHT (
    MERNO VARCHAR2(9) PRIMARY KEY NOT NULL,
    MERNAME VARCHAR(50) NOT NULL
);
CREATE SEQUENCE MER_SEQ
    START WITH 1
    INCREMENT BY 1;
    
-----------------------建立會員權限表格-----------------------

CREATE TABLE MEMAUTH (
    MEMNO VARCHAR2(9) REFERENCES MEMBER(MEMNO) NOT NULL,
    MERNO VARCHAR2(9) REFERENCES MEMRIGHT(MERNO) NOT NULL
);

-----------------------建立管理員表格-----------------------

CREATE TABLE EMPLOYEE(
EMPNO VARCHAR2(9) PRIMARY KEY NOT NULL,
EMPNAME VARCHAR2(20) NOT NULL,
EMPPWD VARCHAR2(10) NOT NULL,
EMPGEN NUMBER(1, 0) NOT NULL CONSTRAINT GENDER_EMPGEN CHECK(EMPGEN =0 OR EMPGEN=1), --0=女, 1=男
EMPPHONE VARCHAR2(15) NOT NULL,
EMPCELL VARCHAR2(15) NOT NULL,
EMPMAIL VARCHAR2(20) NOT NULL,
EMPDEPT VARCHAR2(10) NOT NULL,
EMPPOSI VARCHAR2(10) NOT NULL,
EMPSAL NUMBER(10, 2) NOT NULL,
EMPDOE DATE NOT NULL,
EMPPIC BLOB
);

CREATE SEQUENCE SEQ_EMP_EMPNO
START WITH 1
INCREMENT BY 1;

INSERT INTO EMPLOYEE(EMPNO, EMPNAME, EMPPWD, EMPGEN, EMPPHONE, EMPCELL, EMPMAIL, EMPDEPT, EMPPOSI, EMPSAL, EMPDOE) VALUES('EMP'||LPAD(to_char(SEQ_EMP_EMPNO.NEXTVAL), 6 , '0'), 'Peter', '123456', 1, '03-4257387', '0987654321', 'peter@gmail.com', 'ENG', 'Manager', 200000, to_date('2003-01-05', 'yyyy-mm-dd'));
INSERT INTO EMPLOYEE(EMPNO, EMPNAME, EMPPWD, EMPGEN, EMPPHONE, EMPCELL, EMPMAIL, EMPDEPT, EMPPOSI, EMPSAL, EMPDOE) VALUES('EMP'||LPAD(to_char(SEQ_EMP_EMPNO.NEXTVAL), 6 , '0'), 'David', '123456', 1, '03-4257387', '0911486292', 'david@gmail.com', 'ENG', 'Engineer', 80000, to_date('2010-08-17', 'yyyy-mm-dd'));
INSERT INTO EMPLOYEE(EMPNO, EMPNAME, EMPPWD, EMPGEN, EMPPHONE, EMPCELL, EMPMAIL, EMPDEPT, EMPPOSI, EMPSAL, EMPDOE) VALUES('EMP'||LPAD(to_char(SEQ_EMP_EMPNO.NEXTVAL), 6 , '0'), 'Jaina', '123456', 0, '03-4257387', '0934596754', 'jaina@gmail.com', 'SAL', 'Manager', 100000, to_date('2006-09-05', 'yyyy-mm-dd'));
INSERT INTO EMPLOYEE(EMPNO, EMPNAME, EMPPWD, EMPGEN, EMPPHONE, EMPCELL, EMPMAIL, EMPDEPT, EMPPOSI, EMPSAL, EMPDOE) VALUES('EMP'||LPAD(to_char(SEQ_EMP_EMPNO.NEXTVAL), 6 , '0'), 'Nana', '123456', 0, '03-4257387', '0961397584', 'nana@gmail.com', 'SAL', 'Sales', 35000, to_date('2015-02-03', 'yyyy-mm-dd'));
INSERT INTO EMPLOYEE(EMPNO, EMPNAME, EMPPWD, EMPGEN, EMPPHONE, EMPCELL, EMPMAIL, EMPDEPT, EMPPOSI, EMPSAL, EMPDOE) VALUES('EMP'||LPAD(to_char(SEQ_EMP_EMPNO.NEXTVAL), 6 , '0'), 'Vincent', '123456', 1, '03-4257387', '0933421030', 'vincent@gmail.com', 'SAL', 'Sales', 50000, to_date('2010-07-31', 'yyyy-mm-dd'));
INSERT INTO EMPLOYEE(EMPNO, EMPNAME, EMPPWD, EMPGEN, EMPPHONE, EMPCELL, EMPMAIL, EMPDEPT, EMPPOSI, EMPSAL, EMPDOE) VALUES('EMP'||LPAD(to_char(SEQ_EMP_EMPNO.NEXTVAL), 6 , '0'), '周節輪', '123456', 1, '03-4257387', '0955333216', 'jaychou@gmail.com', 'SAL', 'Sales', 40000, to_date('2012-11-05', 'yyyy-mm-dd'));
INSERT INTO EMPLOYEE(EMPNO, EMPNAME, EMPPWD, EMPGEN, EMPPHONE, EMPCELL, EMPMAIL, EMPDEPT, EMPPOSI, EMPSAL, EMPDOE) VALUES('EMP'||LPAD(to_char(SEQ_EMP_EMPNO.NEXTVAL), 6 , '0'), '曉S', '123456', 0, '03-4257387', '0977129658', 'littles@gmail.com', 'SAL', 'Sales', 65000, to_date('2009-04-28', 'yyyy-mm-dd'));
INSERT INTO EMPLOYEE(EMPNO, EMPNAME, EMPPWD, EMPGEN, EMPPHONE, EMPCELL, EMPMAIL, EMPDEPT, EMPPOSI, EMPSAL, EMPDOE) VALUES('EMP'||LPAD(to_char(SEQ_EMP_EMPNO.NEXTVAL), 6 , '0'), 'Roger', '123456', 1, '03-4257387', '0989659899', 'roger@gmail.com', 'CUS', 'Assistant', 22000, to_date('2017-03-21', 'yyyy-mm-dd'));
INSERT INTO EMPLOYEE(EMPNO, EMPNAME, EMPPWD, EMPGEN, EMPPHONE, EMPCELL, EMPMAIL, EMPDEPT, EMPPOSI, EMPSAL, EMPDOE) VALUES('EMP'||LPAD(to_char(SEQ_EMP_EMPNO.NEXTVAL), 6 , '0'), 'Gordon', '123456', 1, '03-4257387', '0932112565', 'gordon@gmail.com', 'CUS', 'Assitant', 22000, to_date('2017-12-05', 'yyyy-mm-dd'));
INSERT INTO EMPLOYEE(EMPNO, EMPNAME, EMPPWD, EMPGEN, EMPPHONE, EMPCELL, EMPMAIL, EMPDEPT, EMPPOSI, EMPSAL, EMPDOE) VALUES('EMP'||LPAD(to_char(SEQ_EMP_EMPNO.NEXTVAL), 6 , '0'), '蹦蹦姊', '123456', 0, '03-4257387', '0923697411', 'bonbon@gmail.com', 'CUS', 'Assitant', 22000, to_date('2019-01-01', 'yyyy-mm-dd'));

-----------------------建立留言檢舉表格-----------------------

CREATE TABLE BLOGPOSTREPORT (
    BPRNO VARCHAR2(9) PRIMARY KEY NOT NULL,
    POSNO VARCHAR2(9) REFERENCES BLOGPOST(POSNO) NOT NULL,
    BPCNO VARCHAR2(9) REFERENCES BLOGPOSTCOMMENT(BPCNO) NOT NULL,
    MEMNO VARCHAR2(9) REFERENCES MEMBER(MEMNO) NOT NULL,
    EMPNO VARCHAR2(9) REFERENCES EMPLOYEE(EMPNO) NOT NULL,
    BPRTAG VARCHAR2(20) NOT NULL,
    BPRCONTENT CLOB,
    BPRTIME TIMESTAMP,
    BPRSTATUS NUMBER(1),
    BPRRESULT NUMBER(1)
);
CREATE SEQUENCE BPR_SEQ
    START WITH 1
    INCREMENT BY 1;
INSERT INTO BLOGPOSTREPORT (BPRNO, POSNO, BPCNO, MEMNO, EMPNO, BPRTAG, BPRCONTENT, BPRTIME, BPRSTATUS, BPRRESULT)
    VALUES (('BPR' || LPAD(to_char(BPR_SEQ.NEXTVAL), 6 , '0')), 'POS000001', 'BPC000001', 'MEM000001', 'EMP000001', '內容不雅', '怪怪的', SYSTIMESTAMP, 0, 0);

-----------------------建立後台權限表格-----------------------

CREATE TABLE EMPRIGHT(
EMRNO VARCHAR2(9) PRIMARY KEY NOT NULL,
EMRNAME VARCHAR2(50) NOT NULL 
);

CREATE SEQUENCE SEQ_EMR_EMRNO
START WITH 1
INCREMENT BY 1
MINVALUE 1
MAXVALUE 100;
INSERT INTO EMPRIGHT(EMRNO, EMRNAME) VALUES('EMR'||LPAD(to_char(SEQ_EMR_EMRNO.NEXTVAL), 6 , '0'), '文章分類標籤管理');
INSERT INTO EMPRIGHT(EMRNO, EMRNAME) VALUES('EMR'||LPAD(to_char(SEQ_EMR_EMRNO.NEXTVAL), 6 , '0'), 'FAQ管理');
INSERT INTO EMPRIGHT(EMRNO, EMRNAME) VALUES('EMR'||LPAD(to_char(SEQ_EMR_EMRNO.NEXTVAL), 6 , '0'), '最新消息管理');
INSERT INTO EMPRIGHT(EMRNO, EMRNAME) VALUES('EMR'||LPAD(to_char(SEQ_EMR_EMRNO.NEXTVAL), 6 , '0'), '會員權限管理');
INSERT INTO EMPRIGHT(EMRNO, EMRNAME) VALUES('EMR'||LPAD(to_char(SEQ_EMR_EMRNO.NEXTVAL), 6 , '0'), '管理員權限管理');
INSERT INTO EMPRIGHT(EMRNO, EMRNAME) VALUES('EMR'||LPAD(to_char(SEQ_EMR_EMRNO.NEXTVAL), 6 , '0'), '訊息管理');
INSERT INTO EMPRIGHT(EMRNO, EMRNAME) VALUES('EMR'||LPAD(to_char(SEQ_EMR_EMRNO.NEXTVAL), 6 , '0'), '機加酒商品管理');
INSERT INTO EMPRIGHT(EMRNO, EMRNAME) VALUES('EMR'||LPAD(to_char(SEQ_EMR_EMRNO.NEXTVAL), 6 , '0'), '機加酒訂單管理');
INSERT INTO EMPRIGHT(EMRNO, EMRNAME) VALUES('EMR'||LPAD(to_char(SEQ_EMR_EMRNO.NEXTVAL), 6 , '0'), '套裝行程出團管理');
INSERT INTO EMPRIGHT(EMRNO, EMRNAME) VALUES('EMR'||LPAD(to_char(SEQ_EMR_EMRNO.NEXTVAL), 6 , '0'), '套裝行程內容管理');
INSERT INTO EMPRIGHT(EMRNO, EMRNAME) VALUES('EMR'||LPAD(to_char(SEQ_EMR_EMRNO.NEXTVAL), 6 , '0'), '出團訂單管理');
INSERT INTO EMPRIGHT(EMRNO, EMRNAME) VALUES('EMR'||LPAD(to_char(SEQ_EMR_EMRNO.NEXTVAL), 6 , '0'), '推薦自由行管理');
INSERT INTO EMPRIGHT(EMRNO, EMRNAME) VALUES('EMR'||LPAD(to_char(SEQ_EMR_EMRNO.NEXTVAL), 6 , '0'), '自由行景點管理');
INSERT INTO EMPRIGHT(EMRNO, EMRNAME) VALUES('EMR'||LPAD(to_char(SEQ_EMR_EMRNO.NEXTVAL), 6 , '0'), '自由行訂單管理');
INSERT INTO EMPRIGHT(EMRNO, EMRNAME) VALUES('EMR'||LPAD(to_char(SEQ_EMR_EMRNO.NEXTVAL), 6 , '0'), '旅人文章管理');
INSERT INTO EMPRIGHT(EMRNO, EMRNAME) VALUES('EMR'||LPAD(to_char(SEQ_EMR_EMRNO.NEXTVAL), 6 , '0'), '代購管理');
INSERT INTO EMPRIGHT(EMRNO, EMRNAME) VALUES('EMR'||LPAD(to_char(SEQ_EMR_EMRNO.NEXTVAL), 6 , '0'), '查詢代幣交易歷史紀錄');

-----------------------建立管理員權限表格-----------------------

CREATE TABLE EMPAUTHORIZATION(
EMPNO VARCHAR2(9) NOT NULL, CONSTRAINT FK_EMA_EMPNO FOREIGN KEY (EMPNO) REFERENCES EMPLOYEE(EMPNO),
EMRNO VARCHAR2(9) NOT NULL, CONSTRAINT FK_EMA_EMRNO FOREIGN KEY (EMRNO) REFERENCES EMPRIGHT(EMRNO), CONSTRAINT PK_EMPNO_EMRNO PRIMARY KEY (EMPNO, EMRNO), 
EMASTATE NUMBER(1, 0) NOT NULL CONSTRAINT STATE_EMASTATE CHECK(EMASTATE =0 OR EMASTATE=1) --0停權, 1開通
);

INSERT INTO EMPAUTHORIZATION(EMPNO, EMRNO, EMASTATE) VALUES('EMP000001', 'EMR000001', 1);
INSERT INTO EMPAUTHORIZATION(EMPNO, EMRNO, EMASTATE) VALUES('EMP000001', 'EMR000002', 1);
INSERT INTO EMPAUTHORIZATION(EMPNO, EMRNO, EMASTATE) VALUES('EMP000001', 'EMR000003', 1);
INSERT INTO EMPAUTHORIZATION(EMPNO, EMRNO, EMASTATE) VALUES('EMP000001', 'EMR000004', 1);
INSERT INTO EMPAUTHORIZATION(EMPNO, EMRNO, EMASTATE) VALUES('EMP000001', 'EMR000005', 1);
INSERT INTO EMPAUTHORIZATION(EMPNO, EMRNO, EMASTATE) VALUES('EMP000001', 'EMR000006', 1);
INSERT INTO EMPAUTHORIZATION(EMPNO, EMRNO, EMASTATE) VALUES('EMP000001', 'EMR000007', 1);
INSERT INTO EMPAUTHORIZATION(EMPNO, EMRNO, EMASTATE) VALUES('EMP000001', 'EMR000008', 1);
INSERT INTO EMPAUTHORIZATION(EMPNO, EMRNO, EMASTATE) VALUES('EMP000001', 'EMR000009', 1);
INSERT INTO EMPAUTHORIZATION(EMPNO, EMRNO, EMASTATE) VALUES('EMP000001', 'EMR000010', 1);
INSERT INTO EMPAUTHORIZATION(EMPNO, EMRNO, EMASTATE) VALUES('EMP000001', 'EMR000011', 1);
INSERT INTO EMPAUTHORIZATION(EMPNO, EMRNO, EMASTATE) VALUES('EMP000001', 'EMR000012', 1);
INSERT INTO EMPAUTHORIZATION(EMPNO, EMRNO, EMASTATE) VALUES('EMP000001', 'EMR000013', 1);
INSERT INTO EMPAUTHORIZATION(EMPNO, EMRNO, EMASTATE) VALUES('EMP000001', 'EMR000014', 1);
INSERT INTO EMPAUTHORIZATION(EMPNO, EMRNO, EMASTATE) VALUES('EMP000001', 'EMR000015', 1);
INSERT INTO EMPAUTHORIZATION(EMPNO, EMRNO, EMASTATE) VALUES('EMP000001', 'EMR000016', 1);
INSERT INTO EMPAUTHORIZATION(EMPNO, EMRNO, EMASTATE) VALUES('EMP000001', 'EMR000017', 1);
INSERT INTO EMPAUTHORIZATION(EMPNO, EMRNO, EMASTATE) VALUES('EMP000002', 'EMR000001', 1);
INSERT INTO EMPAUTHORIZATION(EMPNO, EMRNO, EMASTATE) VALUES('EMP000002', 'EMR000002', 1);
INSERT INTO EMPAUTHORIZATION(EMPNO, EMRNO, EMASTATE) VALUES('EMP000002', 'EMR000003', 1);
INSERT INTO EMPAUTHORIZATION(EMPNO, EMRNO, EMASTATE) VALUES('EMP000002', 'EMR000004', 1);
INSERT INTO EMPAUTHORIZATION(EMPNO, EMRNO, EMASTATE) VALUES('EMP000002', 'EMR000005', 1);
INSERT INTO EMPAUTHORIZATION(EMPNO, EMRNO, EMASTATE) VALUES('EMP000002', 'EMR000006', 1);
INSERT INTO EMPAUTHORIZATION(EMPNO, EMRNO, EMASTATE) VALUES('EMP000002', 'EMR000007', 1);
INSERT INTO EMPAUTHORIZATION(EMPNO, EMRNO, EMASTATE) VALUES('EMP000002', 'EMR000008', 1);
INSERT INTO EMPAUTHORIZATION(EMPNO, EMRNO, EMASTATE) VALUES('EMP000002', 'EMR000009', 1);
INSERT INTO EMPAUTHORIZATION(EMPNO, EMRNO, EMASTATE) VALUES('EMP000002', 'EMR000010', 1);
INSERT INTO EMPAUTHORIZATION(EMPNO, EMRNO, EMASTATE) VALUES('EMP000002', 'EMR000011', 1);
INSERT INTO EMPAUTHORIZATION(EMPNO, EMRNO, EMASTATE) VALUES('EMP000002', 'EMR000012', 1);
INSERT INTO EMPAUTHORIZATION(EMPNO, EMRNO, EMASTATE) VALUES('EMP000002', 'EMR000013', 1);
INSERT INTO EMPAUTHORIZATION(EMPNO, EMRNO, EMASTATE) VALUES('EMP000002', 'EMR000014', 1);
INSERT INTO EMPAUTHORIZATION(EMPNO, EMRNO, EMASTATE) VALUES('EMP000002', 'EMR000015', 1);
INSERT INTO EMPAUTHORIZATION(EMPNO, EMRNO, EMASTATE) VALUES('EMP000002', 'EMR000016', 1);
INSERT INTO EMPAUTHORIZATION(EMPNO, EMRNO, EMASTATE) VALUES('EMP000002', 'EMR000017', 1);
INSERT INTO EMPAUTHORIZATION(EMPNO, EMRNO, EMASTATE) VALUES('EMP000003', 'EMR000001', 0);
INSERT INTO EMPAUTHORIZATION(EMPNO, EMRNO, EMASTATE) VALUES('EMP000003', 'EMR000002', 0);
INSERT INTO EMPAUTHORIZATION(EMPNO, EMRNO, EMASTATE) VALUES('EMP000003', 'EMR000003', 0);
INSERT INTO EMPAUTHORIZATION(EMPNO, EMRNO, EMASTATE) VALUES('EMP000003', 'EMR000004', 0);
INSERT INTO EMPAUTHORIZATION(EMPNO, EMRNO, EMASTATE) VALUES('EMP000003', 'EMR000005', 0);
INSERT INTO EMPAUTHORIZATION(EMPNO, EMRNO, EMASTATE) VALUES('EMP000003', 'EMR000006', 1);
INSERT INTO EMPAUTHORIZATION(EMPNO, EMRNO, EMASTATE) VALUES('EMP000003', 'EMR000007', 1);
INSERT INTO EMPAUTHORIZATION(EMPNO, EMRNO, EMASTATE) VALUES('EMP000003', 'EMR000008', 1);
INSERT INTO EMPAUTHORIZATION(EMPNO, EMRNO, EMASTATE) VALUES('EMP000003', 'EMR000009', 1);
INSERT INTO EMPAUTHORIZATION(EMPNO, EMRNO, EMASTATE) VALUES('EMP000003', 'EMR000010', 1);
INSERT INTO EMPAUTHORIZATION(EMPNO, EMRNO, EMASTATE) VALUES('EMP000003', 'EMR000011', 1);
INSERT INTO EMPAUTHORIZATION(EMPNO, EMRNO, EMASTATE) VALUES('EMP000003', 'EMR000012', 1);
INSERT INTO EMPAUTHORIZATION(EMPNO, EMRNO, EMASTATE) VALUES('EMP000003', 'EMR000013', 1);
INSERT INTO EMPAUTHORIZATION(EMPNO, EMRNO, EMASTATE) VALUES('EMP000003', 'EMR000014', 1);
INSERT INTO EMPAUTHORIZATION(EMPNO, EMRNO, EMASTATE) VALUES('EMP000003', 'EMR000015', 1);
INSERT INTO EMPAUTHORIZATION(EMPNO, EMRNO, EMASTATE) VALUES('EMP000003', 'EMR000016', 1);
INSERT INTO EMPAUTHORIZATION(EMPNO, EMRNO, EMASTATE) VALUES('EMP000003', 'EMR000017', 1);

-----------------------建立業務訊息表格-----------------------

CREATE TABLE SALES_MESSAGE(
SMENO VARCHAR2(9) PRIMARY KEY NOT NULL,
MEMNO VARCHAR2(9) NOT NULL, CONSTRAINT FK_SME_MEMNO FOREIGN KEY (MEMNO) REFERENCES MEMBER(MEMNO),
EMPNO VARCHAR2(9) NOT NULL, CONSTRAINT FK_SME_EMPNO FOREIGN KEY (EMPNO) REFERENCES EMPLOYEE(EMPNO),
SMECON CLOB,
SMETIME TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);

CREATE SEQUENCE SEQ_SME_SMENO
START WITH 1
INCREMENT BY 1;

INSERT INTO SALES_MESSAGE(SMENO, MEMNO, EMPNO, SMECON, SMETIME) VALUES('SME'||LPAD(to_char(SEQ_SME_SMENO.NEXTVAL), 6, '0'), 'MEM000001', 'EMP000001', 'THIS IS TEST', CURRENT_TIMESTAMP);


-----------------------建立訂單_機加酒表格-----------------------

CREATE TABLE PLANEHOTELORDER(
    PHONO VARCHAR2(12) NOT NULL,
    PHOOWNER VARCHAR2(30) NOT NULL,
    PHOPHONE VARCHAR2(15) NOT NULL,
    PHOMAIL VARCHAR2(50) NOT NULL,
    PHOSTDATE DATE NOT NULL,
    PHOSTATUS NUMBER(1) NOT NULL,
    PHOMARK CLOB,
    PHOVISA VARCHAR2(50) NOT NULL,
    PHOTOTAL NUMBER(10) NOT NULL,
    MEMNO VARCHAR2(12) NOT NULL,
    CONSTRAINT PLANEHOTELORDER_PK PRIMARY KEY(PHONO),
    CONSTRAINT PLANEHOTELORDER_FK FOREIGN KEY(MEMNO) REFERENCES MEMBER(MEMNO));

CREATE SEQUENCE PHO_SEQ
INCREMENT BY 1
START WITH 1
NOMAXVALUE;

INSERT INTO PLANEHOTELORDER VALUES ('PHO'||LPAD(TO_CHAR(PHO_SEQ.NEXTVAL),6,'0'), '姆斯', '0921568221', 'CHIC@yahoo.com.tw', sysdate, 0,' ' ,'1234-5678-4321-9876',100000 ,'MEM000001');
INSERT INTO PLANEHOTELORDER VALUES ('PHO'||LPAD(TO_CHAR(PHO_SEQ.NEXTVAL),6,'0'), '首中', '0937916556', 'BOBO@GMAIL.COM', sysdate, 0,' ' ,'1234-5678-4321-9876',50000 ,'MEM000001');
INSERT INTO PLANEHOTELORDER VALUES ('PHO'||LPAD(TO_CHAR(PHO_SEQ.NEXTVAL),6,'0'), '隆界', '0956337863', 'BABY@yahoo.com.tw', sysdate, 0,' ' ,'1234-5678-4321-9876',500000000 ,'MEM000001');
    
-----------------------建立機加酒商品表格-----------------------

CREATE TABLE PLANEHOTEL(
    PAHNO VARCHAR2(12) NOT NULL,
    PAHNAME VARCHAR2(100) NOT NULL,
    PAHINTRO CLOB NOT NULL,
    PAHCONTENT CLOB NOT NULL,
    PAHPRICE NUMBER(10) NOT NULL,
    PAHCOUNTRY VARCHAR2(50) NOT NULL,
    PAHNUM NUMBER(5) NOT NULL,
    PAHSTDATE DATE NOT NULL,
    PAHENDDATE DATE NOT NULL,
    PAHDOWN TIMESTAMP NOT NULL,
    PAHSTATUS NUMBER(1) NOT NULL,
    PAHPC1 BLOB,
    PAHPC2 BLOB,
    PAHPC3 BLOB,
    PAHPC4 BLOB,
    PAHPC5 BLOB,
    EMPNO VARCHAR2(12) NOT NULL,
    CONSTRAINT PLANEHOTEL_PK PRIMARY KEY(PAHNO),
    CONSTRAINT PLANEHOTEL_FK FOREIGN KEY(EMPNO) REFERENCES EMPLOYEE(EMPNO));

CREATE SEQUENCE PH_SEQ
INCREMENT BY 1
START WITH 1
NOMAXVALUE;

INSERT INTO PLANEHOTEL VALUES('PAH'||LPAD(TO_CHAR(PH_SEQ.NEXTVAL),6,'0'), '東京豪華五日遊', '好好玩', '超級好玩', 18888, 'JAPAN', '10', to_date('2019-4-15','yyyy-mm-dd'), to_date('2019-4-18','yyyy-mm-dd'), to_date('2019-4-10 23:59:59','yyyy-mm-dd hh24:mi:ss'), 0, '', '', '', '', '', 'EMP000001' );
INSERT INTO PLANEHOTEL VALUES('PAH'||LPAD(TO_CHAR(PH_SEQ.NEXTVAL),6,'0'), '倫敦斯文里三日遊', '66666', '無敵好玩', 99999, 'LONDON', '15', to_date('2019-4-15','yyyy-mm-dd'), to_date('2019-4-17','yyyy-mm-dd'), to_date('2019-4-10 23:59:59','yyyy-mm-dd hh24:mi:ss'), 0, '', '', '', '', '', 'EMP000001' );
INSERT INTO PLANEHOTEL VALUES('PAH'||LPAD(TO_CHAR(PH_SEQ.NEXTVAL),6,'0'), '法國愛情摩天輪', '愛情產業鏈', '有女朋友就好玩', 3000, 'FRENCH', '2', to_date('2019-4-15','yyyy-mm-dd'), to_date('2019-4-19','yyyy-mm-dd'), to_date('2019-4-10 23:59:59','yyyy-mm-dd hh24:mi:ss'), 0, '', '', '', '', '', 'EMP000001' );


-----------------------建立機加酒訂單明細表格-----------------------

CREATE TABLE PLANEHOTELDETAIL(
    PAHNO VARCHAR2(12) NOT NULL,
    PHONO VARCHAR2(12) NOT NULL,
    PHDNUM NUMBER(10) NOT NULL,
    CONSTRAINT PLANEHOTELDETAIL_PK PRIMARY KEY(PAHNO,PHONO),
    CONSTRAINT PLANEHOTELDETAIL_FK1 FOREIGN KEY(PAHNO) REFERENCES PLANEHOTEL(PAHNO),
    CONSTRAINT PLANEHOTELDETAIL_FK2 FOREIGN KEY(PHONO) REFERENCES PLANEHOTELORDER(PHONO));
 
INSERT INTO PLANEHOTELDETAIL VALUES ('PAH000001', 'PHO000002',5);
INSERT INTO PLANEHOTELDETAIL VALUES ('PAH000002', 'PHO000002',5);
INSERT INTO PLANEHOTELDETAIL VALUES ('PAH000003', 'PHO000003',5);

-----------------------建立最新消息表格-----------------------

CREATE TABLE NEWS(
    NEWNO VARCHAR2(12) NOT NULL,
    NEWCONTENT CLOB NOT NULL,
    NEWSTDATE DATE NOT NULL,
    NEWENDDATE DATE NOT NULL,
    NEWPC1 BLOB,
    NEWPC2 BLOB,
    EMPNO VARCHAR2(12) NOT NULL,
    CONSTRAINT NEWS_PK PRIMARY KEY (NEWNO),
    CONSTRAINT NEWS_FK FOREIGN KEY (EMPNO) REFERENCES EMPLOYEE(EMPNO));
    
CREATE SEQUENCE NEWS_SEQ
INCREMENT BY 1
START WITH 1
NOMAXVALUE;

INSERT INTO NEWS VALUES ('NEW'||LPAD(TO_CHAR(NEWS_SEQ.NEXTVAL),6,'0'), '套裝行程想一個', to_date('2019-1-17','yyyy-mm-dd'), to_date('2019-4-20 23:59:59','yyyy-mm-dd hh24:mi:ss'), '', '', 'EMP000001');
INSERT INTO NEWS VALUES ('NEW'||LPAD(TO_CHAR(NEWS_SEQ.NEXTVAL),6,'0'), '機加酒想一個', to_date('2019-1-17','yyyy-mm-dd'), to_date('2019-4-20 23:59:59','yyyy-mm-dd hh24:mi:ss'), '', '', 'EMP000001');
INSERT INTO NEWS VALUES ('NEW'||LPAD(TO_CHAR(NEWS_SEQ.NEXTVAL),6,'0'), '自由行想一個', to_date('2019-1-17','yyyy-mm-dd'), to_date('2019-4-20 23:59:59','yyyy-mm-dd hh24:mi:ss'), '', '', 'EMP000001');

-----------------------建立FAQ表格-----------------------

CREATE TABLE FAQ(
    FAQNO VARCHAR2(12) NOT NULL,
    FAQCONTENT CLOB NOT NULL,
    FAQSTYLE NUMBER(1) NOT NULL,
    EMPNO VARCHAR2(12) NOT NULL,
    CONSTRAINT FAQ_PK PRIMARY KEY (FAQNO),
    CONSTRAINT FAQ_FK FOREIGN KEY (EMPNO) REFERENCES EMPLOYEE(EMPNO));
    
CREATE SEQUENCE FAQ_SEQ
INCREMENT BY 1
START WITH 1
NOMAXVALUE;

INSERT INTO FAQ VALUES ('FAQ'||LPAD(TO_CHAR(FAQ_SEQ.NEXTVAL),6,'0'), '代購想一個', 0, 'EMP000001');
INSERT INTO FAQ VALUES ('FAQ'||LPAD(TO_CHAR(FAQ_SEQ.NEXTVAL),6,'0'), '套裝行程想一個', 1, 'EMP000001');
INSERT INTO FAQ VALUES ('FAQ'||LPAD(TO_CHAR(FAQ_SEQ.NEXTVAL),6,'0'), '機加酒想一個', 2, 'EMP000001');
INSERT INTO FAQ VALUES ('FAQ'||LPAD(TO_CHAR(FAQ_SEQ.NEXTVAL),6,'0'), '自由行想一個', 3, 'EMP000001');

-----------------------建立代幣交易紀錄表格-----------------------

CREATE TABLE ACCOUNTRECORD(
  ACRID VARCHAR2(12)PRIMARY KEY NOT NULL,
  MEMNO VARCHAR2(12)REFERENCES MEMBER(MEMNO) NOT NULL,
  ACRTIME TIMESTAMP,
  ACRPRICE NUMBER(10,0),
  ACRSOURCE NUMBER(1) NOT NULL,
  ACREND VARCHAR2(100),
  ACRTOTAL NUMBER(15,0));

CREATE SEQUENCE ACRID_SEQ
INCREMENT BY 1
START WITH 1
NOMAXVALUE
NOCYCLE
NOCACHE;

INSERT INTO ACCOUNTRECORD(ACRID,MEMNO,ACRTIME,ACRPRICE,ACRSOURCE,ACREND,ACRTOTAL)VALUES('ACR'||LPAD(to_char(ACRID_SEQ.NEXTVAL),6,'0'),'MEM000001',CURRENT_TIMESTAMP,6000,1,'儲值',6000);
INSERT INTO ACCOUNTRECORD(ACRID,MEMNO,ACRTIME,ACRPRICE,ACRSOURCE,ACREND,ACRTOTAL)VALUES('ACR'||LPAD(to_char(ACRID_SEQ.NEXTVAL),6,'0'),'MEM000001',CURRENT_TIMESTAMP,-2300,0,'與會員MEM000002交易成功',3700);
INSERT INTO ACCOUNTRECORD(ACRID,MEMNO,ACRTIME,ACRPRICE,ACRSOURCE,ACREND,ACRTOTAL)VALUES('ACR'||LPAD(to_char(ACRID_SEQ.NEXTVAL),6,'0'),'MEM000002',CURRENT_TIMESTAMP,2300,1,'與會員MEM000001交易成功',2300);
INSERT INTO ACCOUNTRECORD(ACRID,MEMNO,ACRTIME,ACRPRICE,ACRSOURCE,ACREND,ACRTOTAL)VALUES('ACR'||LPAD(to_char(ACRID_SEQ.NEXTVAL),6,'0'),'MEM000001',CURRENT_TIMESTAMP,-700,0,'與會員MEM000003交易成功',3000);
INSERT INTO ACCOUNTRECORD(ACRID,MEMNO,ACRTIME,ACRPRICE,ACRSOURCE,ACREND,ACRTOTAL)VALUES('ACR'||LPAD(to_char(ACRID_SEQ.NEXTVAL),6,'0'),'MEM000003',CURRENT_TIMESTAMP,700,1,'與會員MEM000001交易成功',700);
INSERT INTO ACCOUNTRECORD(ACRID,MEMNO,ACRTIME,ACRPRICE,ACRSOURCE,ACREND,ACRTOTAL)VALUES('ACR'||LPAD(to_char(ACRID_SEQ.NEXTVAL),6,'0'),'MEM000001',CURRENT_TIMESTAMP,-3000,0,'與會員MEM000002交易成功',0);
INSERT INTO ACCOUNTRECORD(ACRID,MEMNO,ACRTIME,ACRPRICE,ACRSOURCE,ACREND,ACRTOTAL)VALUES('ACR'||LPAD(to_char(ACRID_SEQ.NEXTVAL),6,'0'),'MEM000002',CURRENT_TIMESTAMP,3000,1,'與會員MEM000001交易成功',5300);

-----------------------建立代購商品表格-----------------------

CREATE TABLE PURCHASE(
  PURID VARCHAR2(12)PRIMARY KEY NOT NULL,
  MEMNO VARCHAR2(12)REFERENCES MEMBER(MEMNO) NOT NULL,
  PURNAME VARCHAR2(100),
  PURCONTENT VARCHAR2(300),
  PURSORT NUMBER(10),
  PURURL VARCHAR2(200),
  PURCOUNTRY VARCHAR2(10),
  PURDELIVERY VARCHAR2(10),
  PURREPRICE NUMBER(10),
  PURPRICING NUMBER(10),
  PUROBTAINED TIMESTAMP,
  PURTIME TIMESTAMP,
  PURRECEIPT NUMBER(1),
  PURSTATUS NUMBER(1),
  PURPIC BLOB,
  PUREXTIME TIMESTAMP,
  PURSTOCK NUMBER(3),
  PURSELL NUMBER(3),
  PURLIMIT NUMBER(2),
  PURSAVETIME TIMESTAMP);

CREATE SEQUENCE PURID_SEQ
INCREMENT BY 1
START WITH 1
NOMAXVALUE
NOCYCLE
NOCACHE;

INSERT INTO PURCHASE(PURID,MEMNO,PURNAME,PURCONTENT,PURSORT,PURURL,PURCOUNTRY,PURDELIVERY,PURREPRICE,PURPRICING,PUROBTAINED,PURTIME,PURRECEIPT,PURSTATUS,PURPIC,PUREXTIME,PURSTOCK,PURSELL,PURLIMIT,PURSAVETIME)VALUES('PUR'||LPAD(to_char(PURID_SEQ.NEXTVAL),6,'0'),'MEM000002','亞太限定樂高','僅限中國和部分亞太國家限定發售的合組「LEGO 80102 舞龍」(Dragon Dance)日本太回火熱搶購中',2,'https://api.dropbuy.global/deeplink/recommendationdetail/8189','日本','臺灣',2885,3000,TO_TIMESTAMP('2019-02-21 18:00:00', 'YYYY-MM-DD HH24:MI:SS'),CURRENT_TIMESTAMP,0,0,'',TO_TIMESTAMP('2019-02-22 18:00:00', 'YYYY-MM-DD HH24:MI:SS'),10,1,3,CURRENT_TIMESTAMP);
INSERT INTO PURCHASE(PURID,MEMNO,PURNAME,PURCONTENT,PURSORT,PURURL,PURCOUNTRY,PURDELIVERY,PURREPRICE,PURPRICING,PUROBTAINED,PURTIME,PURRECEIPT,PURSTATUS,PURPIC,PUREXTIME,PURSTOCK,PURSELL,PURLIMIT,PURSAVETIME)VALUES('PUR'||LPAD(to_char(PURID_SEQ.NEXTVAL),6,'0'),'MEM000003','日本桂新堂豬年限定蝦餅禮盒(11入)','日本桂新堂 豬年限定蝦餅禮盒，在蝦餅印上節慶吉祥圖案，滿滿的年節氛圍，非常適合豬年送禮 ?',2,'https://www.dropbuy.global/recommendation/8109','日本','臺灣',690,700,TO_TIMESTAMP('2019-02-19 18:00:00', 'YYYY-MM-DD HH24:MI:SS'),CURRENT_TIMESTAMP,1,1,'',TO_TIMESTAMP('2019-02-23 18:00:00', 'YYYY-MM-DD HH24:MI:SS'),15,1,2,CURRENT_TIMESTAMP);
INSERT INTO PURCHASE(PURID,MEMNO,PURNAME,PURCONTENT,PURSORT,PURURL,PURCOUNTRY,PURDELIVERY,PURREPRICE,PURPRICING,PUROBTAINED,PURTIME,PURRECEIPT,PURSTATUS,PURPIC,PUREXTIME,PURSTOCK,PURSELL,PURLIMIT,PURSAVETIME)VALUES('PUR'||LPAD(to_char(PURID_SEQ.NEXTVAL),6,'0'),'MEM000002','櫻花限定迪士尼小熊維尼(大隻)','商品預購中，2/1 日本迪士尼商店才開賣',2,'https://www.dropbuy.global/recommendation/8343','日本','臺灣',1800,2300,TO_TIMESTAMP('2019-02-21 18:00:00', 'YYYY-MM-DD HH24:MI:SS'),CURRENT_TIMESTAMP,0,1,'',TO_TIMESTAMP('2019-02-24 18:00:00', 'YYYY-MM-DD HH24:MI:SS'),5,1,4,CURRENT_TIMESTAMP);

-----------------------建立代購商品檢舉表格-----------------------

CREATE TABLE PURCHASEREPORT(
  PREID VARCHAR2(12)PRIMARY KEY NOT NULL,
  MEMNO VARCHAR2(12)REFERENCES MEMBER(MEMNO) NOT NULL,
  PURID VARCHAR2(12)REFERENCES PURCHASE(PURID) NOT NULL,
  EMPNO VARCHAR2(12)REFERENCES EMPLOYEE(EMPNO) NOT NULL,
  PRECAUSE VARCHAR2(300),
  PRETIME TIMESTAMP,
  PRESTATUS NUMBER(1),
  PRELABEL NUMBER(2),
  PRERESULT NUMBER(1));

CREATE SEQUENCE PREID_SEQ
INCREMENT BY 1
START WITH 1
NOMAXVALUE
NOCYCLE
NOCACHE;

INSERT INTO PURCHASEREPORT(PREID,MEMNO,PURID,EMPNO,PRECAUSE,PRETIME,PRESTATUS,PRELABEL,PRERESULT)VALUES('PRE'||LPAD(to_char(PREID_SEQ.NEXTVAL),6,'0'),'MEM000001','PUR000003','EMP000001','代購內容不當',CURRENT_TIMESTAMP,0,11,'');
INSERT INTO PURCHASEREPORT(PREID,MEMNO,PURID,EMPNO,PRECAUSE,PRETIME,PRESTATUS,PRELABEL,PRERESULT)VALUES('PRE'||LPAD(to_char(PREID_SEQ.NEXTVAL),6,'0'),'MEM000002','PUR000003','EMP000001','代購內容不當',CURRENT_TIMESTAMP,0,11,'');
INSERT INTO PURCHASEREPORT(PREID,MEMNO,PURID,EMPNO,PRECAUSE,PRETIME,PRESTATUS,PRELABEL,PRERESULT)VALUES('PRE'||LPAD(to_char(PREID_SEQ.NEXTVAL),6,'0'),'MEM000003','PUR000002','EMP000001','代購內容不當',CURRENT_TIMESTAMP,0,11,'');

-----------------------建立訂單_代購商品表格-----------------------

CREATE TABLE PURCHASEORDER(
  PORID VARCHAR2(12)PRIMARY KEY NOT NULL,
  PURID VARCHAR2(12)REFERENCES PURCHASE(PURID) NOT NULL,
  MEMNO VARCHAR2(12)REFERENCES MEMBER(MEMNO) NOT NULL,
  PORMEMNAME VARCHAR2(12),
  PORPRICE NUMBER(10,0),
  PORTIME TIMESTAMP,
  PORADDRESS VARCHAR2(100),
  PORTEL VARCHAR2(10),
  PORSTATUS NUMBER(1),
  PORSTATUSTIME TIMESTAMP,
  PORBUYSCORE NUMBER(2),
  PORBUYCONTENT VARCHAR2(100),
  PORBUYTIME TIMESTAMP,
  PORSELLSCORE NUMBER(2),
  PORSELLCONTENT VARCHAR2(100),
  PORSELLTIME TIMESTAMP,
  PORSUM NUMBER(3),
  PORLOGISTICS NUMBER(1),
  PORQR BLOB
  );

CREATE SEQUENCE PORID_SEQ
INCREMENT BY 1
START WITH 1
NOMAXVALUE
NOCYCLE
NOCACHE;

INSERT INTO PURCHASEORDER(PORID,PURID,MEMNO,PORMEMNAME,PORPRICE,PORTIME,PORADDRESS,PORTEL,
PORSTATUS,PORSTATUSTIME,PORBUYSCORE,PORBUYCONTENT,PORBUYTIME,PORSELLSCORE,PORSELLCONTENT,
PORSELLTIME,PORSUM,PORLOGISTICS,PORQR)VALUES('POR'||LPAD(to_char(PORID_SEQ.NEXTVAL),6,'0'),
'PUR000002','MEM000001','吳先生',700,CURRENT_TIMESTAMP,'桃園市中壢資策會','0970852426',0,
systimestamp + INTERVAL '01:00' HOUR TO MINUTE,5,'優良賣家',
systimestamp + INTERVAL '03:00' HOUR TO MINUTE,5,'優良買家',
systimestamp + INTERVAL '02:00' HOUR TO MINUTE,1,2,null);
INSERT INTO PURCHASEORDER(PORID,PURID,MEMNO,PORMEMNAME,PORPRICE,PORTIME,PORADDRESS,PORTEL,
PORSTATUS,PORSTATUSTIME,PORBUYSCORE,PORBUYCONTENT,PORBUYTIME,PORSELLSCORE,PORSELLCONTENT,
PORSELLTIME,PORSUM,PORLOGISTICS,PORQR)VALUES('POR'||LPAD(to_char(PORID_SEQ.NEXTVAL),6,'0'),
'PUR000003','MEM000001','吳先生',2300,CURRENT_TIMESTAMP,'桃園市中壢資策會','0970852426',0,
systimestamp + INTERVAL '01:00' HOUR TO MINUTE,5,'優良賣家',
systimestamp + INTERVAL '03:00' HOUR TO MINUTE,5,'優良買家',
systimestamp + INTERVAL '02:00' HOUR TO MINUTE,1,2,null);
INSERT INTO PURCHASEORDER(PORID,PURID,MEMNO,PORMEMNAME,PORPRICE,PORTIME,PORADDRESS,PORTEL,
PORSTATUS,PORSTATUSTIME,PORBUYSCORE,PORBUYCONTENT,PORBUYTIME,PORSELLSCORE,PORSELLCONTENT,
PORSELLTIME,PORSUM,PORLOGISTICS,PORQR)VALUES('POR'||LPAD(to_char(PORID_SEQ.NEXTVAL),6,'0'),
'PUR000001','MEM000001','吳先生',2885,CURRENT_TIMESTAMP,'桃園市中壢資策會','0970852426',0,
systimestamp + INTERVAL '01:00' HOUR TO MINUTE,5,'優良賣家',
systimestamp + INTERVAL '03:00' HOUR TO MINUTE,5,'優良買家',
systimestamp + INTERVAL '02:00' HOUR TO MINUTE,1,2,null);

-----------------------建立行程表格-----------------------

CREATE TABLE TRIP (
    TRINO VARCHAR2(9) PRIMARY KEY NOT NULL,
    MEMNO VARCHAR2(9) REFERENCES MEMBER(MEMNO) NOT NULL,
    TRINAME VARCHAR2(300) NOT NULL,
    TRIBEGDATE DATE NOT NULL,
    TRIENDDATE DATE NOT NULL,
    TRIPEONUM NUMBER(2),
    TRISTAT NUMBER(1) NOT NULL,
    TRIREMARK VARCHAR2(500)
);
CREATE SEQUENCE TRI_SEQ
START WITH 1
INCREMENT BY 1;
INSERT INTO TRIP VALUES ('TRI'||LPAD(TO_CHAR(TRI_SEQ.NEXTVAL),6,'0'), 'MEM000001', '台北3日遊', TO_DATE('2019-4-1', 'yyyy-mm-dd'), TO_DATE('2019-4-3', 'yyyy-mm-dd'), 2, 0, '吃素,分房睡');
INSERT INTO TRIP VALUES ('TRI'||LPAD(TO_CHAR(TRI_SEQ.NEXTVAL),6,'0'), 'MEM000003', '北海道5日吃貨之旅', TO_DATE('2019-7-21', 'yyyy-mm-dd'), TO_DATE('2019-7-26', 'yyyy-mm-dd'), 1, 0, NULL);
INSERT INTO TRIP VALUES ('TRI'||LPAD(TO_CHAR(TRI_SEQ.NEXTVAL),6,'0'), 'MEM000002', '歐洲7日輕旅行', TO_DATE('2019-9-18', 'yyyy-mm-dd'), TO_DATE('2019-9-25', 'yyyy-mm-dd'), 1, 0, NULL);

-----------------------建立景點表格-----------------------

CREATE TABLE SPOT (
    SPONO VARCHAR2(9) PRIMARY KEY NOT NULL,
    SPONAME VARCHAR2(150) NOT NULL,
    SPOCLASS VARCHAR2(50) NOT NULL,
    SPOCON VARCHAR2(100) NOT NULL,
    SPOCITY VARCHAR2(100) NOT NULL,
    SPOLAT NUMBER(16,13) NOT NULL,
    SPOLONG NUMBER(16,13) NOT NULL,
    SPOADDR VARCHAR2(500) NOT NULL,
    SPOCONTENT CLOB,
    SPOPIC BLOB,
    SPOATTRIBUTE NUMBER(1) NOT NULL
);
CREATE SEQUENCE SPO_SEQ
START WITH 1
INCREMENT BY 1;
INSERT INTO SPOT VALUES ('SPO'||LPAD(TO_CHAR(SPO_SEQ.NEXTVAL),6,'0'), '台北101', '景點', '台灣', '台北市', 25.0338009, 121.5644803, '110台北市信義區信義路五段7號', NULL, NULL, 0);
INSERT INTO SPOT VALUES ('SPO'||LPAD(TO_CHAR(SPO_SEQ.NEXTVAL),6,'0'), '國立故宮博物院', '博物館', '台灣', '台北市', 25.1004238, 121.5496498000001, '111台北市士林區至善路二段221號', NULL, NULL, 0);
INSERT INTO SPOT VALUES ('SPO'||LPAD(TO_CHAR(SPO_SEQ.NEXTVAL),6,'0'), '一蘭 台灣台北本店', '美食', '台灣', '台北市', 25.03618495, 121.56854895, '110台北市信義區松仁路97號', NULL, NULL, 0);
INSERT INTO SPOT VALUES ('SPO'||LPAD(TO_CHAR(SPO_SEQ.NEXTVAL),6,'0'), '士林夜市', '美食', '台灣', '台北市', 25.08792015, 121.524068, '111台北市士林區基河路101號', NULL, NULL, 0);
INSERT INTO SPOT VALUES ('SPO'||LPAD(TO_CHAR(SPO_SEQ.NEXTVAL),6,'0'), 'OMNI Nightclub', '夜生活', '台灣', '台北市', 25.0417861, 121.5515753, 'No. 201忠孝東路四段大安區台北市106', NULL, NULL, 0);
INSERT INTO SPOT VALUES ('SPO'||LPAD(TO_CHAR(SPO_SEQ.NEXTVAL),6,'0'), '中央大學', '景點', '台灣', '桃園市', 24.9683445, 121.19566375, '320桃園市中壢區中大路300號', NULL, NULL, 0);
INSERT INTO SPOT VALUES ('SPO'||LPAD(TO_CHAR(SPO_SEQ.NEXTVAL),6,'0'), '圓山大飯店', '飯店', '台灣', '台北市', 25.078313, 121.526136, '10491台北市中山區中山北路四段1號', NULL, NULL, 0);
INSERT INTO SPOT VALUES ('SPO'||LPAD(TO_CHAR(SPO_SEQ.NEXTVAL),6,'0'), '松山文創園區', '景點', '台灣', '台北市', 25.0436839, 121.55935, '110台北市信義區光復南路133號', NULL, NULL, 0);
INSERT INTO SPOT VALUES ('SPO'||LPAD(TO_CHAR(SPO_SEQ.NEXTVAL),6,'0'), '台北福華大飯店', '飯店', '台灣', '台北市', 25.037649, 121.543155, '106台北市大安區仁愛路三段160號', NULL, NULL, 0);
INSERT INTO SPOT VALUES ('SPO'||LPAD(TO_CHAR(SPO_SEQ.NEXTVAL),6,'0'), '中壢觀光夜市', '美食', '台灣', '桃園市', 24.960040, 121.215163, '320桃園市中壢區新明路', NULL, NULL, 0);
INSERT INTO SPOT VALUES ('SPO'||LPAD(TO_CHAR(SPO_SEQ.NEXTVAL),6,'0'), '草悟道', '景點', '台灣', '台中市', 24.148548, 120.664768, '403台中市西區向上北路', NULL, NULL, 0);

-----------------------建立行程明細表格-----------------------

CREATE TABLE TRIPDETAIL (
    TDENO VARCHAR2(9) PRIMARY KEY NOT NULL,
    TRINO VARCHAR2(9) REFERENCES TRIP(TRINO) NOT NULL,
    SPONO VARCHAR2(9) REFERENCES SPOT(SPONO) NOT NULL,
    TDESTART TIMESTAMP,
    TDEFINISH TIMESTAMP,
    TDEDATE VARCHAR2(20) NOT NULL,
    TDESEQ NUMBER(3) NOT NULL,
    TDEREMARK CLOB
);
CREATE SEQUENCE TDE_SEQ
START WITH 1
INCREMENT BY 1;
INSERT INTO TRIPDETAIL VALUES ('TDE'||LPAD(TO_CHAR(TDE_SEQ.NEXTVAL),6,'0'), 'TRI000001', 'SPO000002', TO_DATE('2019-4-1 8:00', 'yyyy-mm-dd hh24:mi'), TO_DATE('2019-4-1 11:00', 'yyyy-mm-dd hh24:mi'), 'D1', 1, NULL);
INSERT INTO TRIPDETAIL VALUES ('TDE'||LPAD(TO_CHAR(TDE_SEQ.NEXTVAL),6,'0'), 'TRI000001', 'SPO000003', TO_DATE('2019-4-1 11:30', 'yyyy-mm-dd hh24:mi'), TO_DATE('2019-4-1 13:00', 'yyyy-mm-dd hh24:mi'), 'D1', 2, NULL);
INSERT INTO TRIPDETAIL VALUES ('TDE'||LPAD(TO_CHAR(TDE_SEQ.NEXTVAL),6,'0'), 'TRI000001', 'SPO000001', TO_DATE('2019-4-1 13:20', 'yyyy-mm-dd hh24:mi'), TO_DATE('2019-4-1 18:00', 'yyyy-mm-dd hh24:mi'), 'D1', 3, NULL);

-----------------------建立訂單_自由行表格-----------------------

CREATE TABLE TRIPORDER (
    TODNO VARCHAR2(9) PRIMARY KEY NOT NULL,
    MEMNO VARCHAR2(9) REFERENCES MEMBER(MEMNO) NOT NULL,
    TRINO VARCHAR2(9) REFERENCES TRIP(TRINO) NOT NULL,
    EMPNO VARCHAR2(9) REFERENCES EMPLOYEE(EMPNO) NOT NULL,
    TODQUO NUMBER(7) CHECK (TODQUO>0) NOT NULL,
    TODDDL DATE NOT NULL,
    TODDATE DATE DEFAULT CURRENT_DATE NOT NULL,
    TODREMARK VARCHAR2(200),
    TODSTAT NUMBER NOT NULL
);
CREATE SEQUENCE TOD_SEQ
START WITH 1
INCREMENT BY 1;
INSERT INTO TRIPORDER VALUES ('TOD'||LPAD(TO_CHAR(TOD_SEQ.NEXTVAL),6,'0'), 'MEM000001', 'TRI000001', 'EMP000002', 3500, TO_DATE('2019-3-3', 'yyyy-mm-dd'), DEFAULT, NULL, 1);
INSERT INTO TRIPORDER VALUES ('TOD'||LPAD(TO_CHAR(TOD_SEQ.NEXTVAL),6,'0'), 'MEM000003', 'TRI000002', 'EMP000002', 14800, TO_DATE('2019-3-29', 'yyyy-mm-dd'), DEFAULT, NULL, 3);
INSERT INTO TRIPORDER VALUES ('TOD'||LPAD(TO_CHAR(TOD_SEQ.NEXTVAL),6,'0'), 'MEM000003', 'TRI000003', 'EMP000001', 9200, TO_DATE('2019-4-5', 'yyyy-mm-dd'), DEFAULT, NULL, 1);

-----------------------建立推薦行程表格-----------------------

CREATE TABLE RECOMMENDTRIP (
    RTRNO VARCHAR2(9) PRIMARY KEY NOT NULL,
    EMPNO VARCHAR2(9) REFERENCES EMPLOYEE(EMPNO) NOT NULL,
    RTRCON VARCHAR2(100) NOT NULL,
    RTRCITY VARCHAR2(100) NOT NULL,
    RTRDAYS NUMBER(2) NOT NULL,
    RTRPEONUM NUMBER(2),
    RTRPREF NUMBER(1) NOT NULL
);
CREATE SEQUENCE RTR_SEQ
START WITH 1
INCREMENT BY 1;
INSERT INTO RECOMMENDTRIP VALUES ('RTR'||LPAD(TO_CHAR(RTR_SEQ.NEXTVAL),6,'0'), 'EMP000002', '台灣', '台中市', 3, NULL, 2);
INSERT INTO RECOMMENDTRIP VALUES ('RTR'||LPAD(TO_CHAR(RTR_SEQ.NEXTVAL),6,'0'), 'EMP000002', '台灣', '台北市', 1, NULL, 1);
INSERT INTO RECOMMENDTRIP VALUES ('RTR'||LPAD(TO_CHAR(RTR_SEQ.NEXTVAL),6,'0'), 'EMP000003', '台灣', '高雄市', 2, NULL, 2);

-----------------------建立推薦行程明細表格-----------------------

CREATE TABLE RECOMMENDTRIPDETAIL (
    RTDNO VARCHAR2(9) PRIMARY KEY NOT NULL,
    RTRNO VARCHAR2(9) REFERENCES RECOMMENDTRIP(RTRNO) NOT NULL,
    SPONO VARCHAR2(9) REFERENCES SPOT(SPONO) NOT NULL,
    RTDSTART TIMESTAMP NOT NULL,
    RTDFINISH TIMESTAMP NOT NULL,
    RTDDAYS VARCHAR2(20) NOT NULL,
    RTDSEQ NUMBER(2) NOT NULL
);
CREATE SEQUENCE RTD_SEQ
START WITH 1
INCREMENT BY 1;
INSERT INTO RECOMMENDTRIPDETAIL VALUES ('RTD'||LPAD(TO_CHAR(RTD_SEQ.NEXTVAL),6,'0'), 'RTR000002', 'SPO000002', TO_DATE('8:30', 'hh24:mi'), TO_DATE('11:30', 'hh24:mi'), 'D1', 1);
INSERT INTO RECOMMENDTRIPDETAIL VALUES ('RTD'||LPAD(TO_CHAR(RTD_SEQ.NEXTVAL),6,'0'), 'RTR000002', 'SPO000003', TO_DATE('12:00', 'hh24:mi'), TO_DATE('13:30', 'hh24:mi'), 'D1', 2);
INSERT INTO RECOMMENDTRIPDETAIL VALUES ('RTD'||LPAD(TO_CHAR(RTD_SEQ.NEXTVAL),6,'0'), 'RTR000002', 'SPO000001', TO_DATE('14:00', 'hh24:mi'), TO_DATE('18:00', 'hh24:mi'), 'D1', 3);

-----------------------建立套裝行程內容表格-----------------------

CREATE TABLE PACKAGE (
  PACNO VARCHAR2(9) PRIMARY KEY NOT NULL,
  EMPNO VARCHAR2(9) NOT NULL,
  PACNAME VARCHAR2(40),
  PACCOUNTRY VARCHAR2(10),
  PACCITY VARCHAR2(40),
  PACTOTALDAY NUMBER(12),
  PACPRICE NUMBER(8,2) CHECK (PACPRICE>0),
  PACDEPOSIT NUMBER(8,2) CHECK (PACDEPOSIT>=0),
  PACDIV VARCHAR2(20),
  PACCONTENT CLOB,
  PACTCHAR1 BLOB,
  PACTCHAR2 BLOB,
  PACREMARK CLOB,
  PACSTATUS NUMBER(8),
  CONSTRAINT PACKAGE_FK FOREIGN KEY(EMPNO) REFERENCES EMPLOYEE(EMPNO)
);

CREATE SEQUENCE PAC_SEQ
INCREMENT BY 1
START WITH 1
NOMAXVALUE;

INSERT INTO PACKAGE VALUES('PAC'||LPAD(TO_CHAR(PAC_SEQ.NEXTVAL),6,'0'),'EMP000001','北海道五日遊','日本','札幌',5,25000,5000,'賞雪',
'北海道五日遊內容','','','注意事項',0);  
INSERT INTO PACKAGE VALUES('PAC'||LPAD(TO_CHAR(PAC_SEQ.NEXTVAL),6,'0'),'EMP000001','戀戀吳哥窟6日遊','柬埔寨','高棉',5,25000,5000,'世界遺產',
'戀戀吳哥窟6日遊內容','','','注意事項',0);
INSERT INTO PACKAGE VALUES('PAC'||LPAD(TO_CHAR(PAC_SEQ.NEXTVAL),6,'0'),'EMP000001','浪漫巴黎香舍八日遊','法國','巴黎',8,98000,47000,'城市',
'法國特色','','','注意事項',0);

-----------------------建立套裝行程出團內容表格-----------------------

CREATE TABLE PACTRIPCONTENT (
  PTPNO VARCHAR2(9) PRIMARY KEY NOT NULL,
  PACNO VARCHAR2(9),
  PTPSTART DATE NOT NULL,
  PTPEND DATE NOT NULL,
  PACSIGNDLE TIMESTAMP,
  PTPNOTICE CLOB,
  PTPVACANCY NUMBER(6,0),
  PTPMINMEN NUMBER(12),
  PTPMAXMEN NUMBER(12),
  PTPSTATUS NUMBER(2),
  PACTIMELOG TIMESTAMP,
  CONSTRAINT PACTRIPCONTENT_FK FOREIGN KEY(PACNO) REFERENCES PACKAGE(PACNO));
  
  CREATE SEQUENCE PACTR_SEQ
  INCREMENT BY 1
  START WITH 1
  NOMAXVALUE;
  
  INSERT INTO PACTRIPCONTENT (PTPNO, PACNO, PTPSTART, PTPEND, PACSIGNDLE, PTPNOTICE, PTPVACANCY, PTPMINMEN, PTPMAXMEN, PTPSTATUS, PACTIMELOG)
    VALUES('PTP'||LPAD(TO_CHAR(PACTR_SEQ.NEXTVAL),6,'0'),'PAC000001',TO_DATE('2019-2-3','YYYY-MM-DD'),TO_DATE('2019-2-8','YYYY-MM-DD'),TO_DATE('2019-1-31 21:02:40','YYYY-MM-DD HH24:MI:SS'),'第一天住xxx',17,15,35,2,TO_DATE('2019-1-31','YYYY-MM-DD'));
  INSERT INTO PACTRIPCONTENT (PTPNO, PACNO, PTPSTART, PTPEND, PACSIGNDLE, PTPNOTICE, PTPVACANCY, PTPMINMEN, PTPMAXMEN, PTPSTATUS, PACTIMELOG)
    VALUES('PTP'||LPAD(TO_CHAR(PACTR_SEQ.NEXTVAL),6,'0'),'PAC000002',TO_DATE('2019-2-5','YYYY-MM-DD'),TO_DATE('2019-2-9','YYYY-MM-DD'),TO_DATE('2019-1-30 21:02:40','YYYY-MM-DD HH24:MI:SS'),'第三天住xxx',18,15,35,2,TO_DATE('2019-1-31','YYYY-MM-DD'));
  INSERT INTO PACTRIPCONTENT (PTPNO, PACNO, PTPSTART, PTPEND, PACSIGNDLE, PTPNOTICE, PTPVACANCY, PTPMINMEN, PTPMAXMEN, PTPSTATUS, PACTIMELOG)
    VALUES('PTP'||LPAD(TO_CHAR(PACTR_SEQ.NEXTVAL),6,'0'),'PAC000001',TO_DATE('2019-2-4','YYYY-MM-DD'),TO_DATE('2019-2-10','YYYY-MM-DD'),TO_DATE('2019-1-29 21:02:40','YYYY-MM-DD HH24:MI:SS'),'第四天住xxx',5,15,35,3,TO_DATE('2019-1-31','YYYY-MM-DD'));

-----------------------建立套裝行程訂單表格-----------------------

CREATE TABLE PACORDER(
    PCDORDNO VARCHAR2(9),  
    PTPNO VARCHAR2(9),
    MEMNO VARCHAR2(9),
    PCDTRIPMEN NUMBER(12,0),
    PCDORDDAY DATE,
    PCDPRICE NUMBER(8,2) CHECK (PCDPRICE>=0),
    PCDSTATUS NUMBER(2),
    PCDSECPHONE NUMBER(20),
    PCDFAMDATA CLOB,
    PCDMARK CLOB,
    CONSTRAINT PCD_FK_PACTRIPCONTENT FOREIGN KEY(PTPNO) REFERENCES PACTRIPCONTENT(PTPNO),
    CONSTRAINT PCD_FK_MEMBER         FOREIGN KEY(MEMNO) REFERENCES MEMBER(MEMNO)
    );   
   
   CREATE SEQUENCE PCD_SEQ
   INCREMENT BY 1
   START WITH 1
   NOMAXVALUE;
   
  
   INSERT INTO PACORDER (PCDORDNO , PTPNO , MEMNO , PCDTRIPMEN , PCDORDDAY ,PCDPRICE ,PCDSTATUS, PCDSECPHONE,PCDFAMDATA ,PCDMARK)
                        VALUES('PCD'||LPAD(TO_CHAR(PCD_SEQ.NEXTVAL),6,'0'),'PTP000001','MEM000001',6,TO_DATE('2019-2-3','YYYY-MM-DD')
                        ,23000*6,2,097878787,'王大頭 1988-2-2 A123456789','吃素');
   INSERT INTO PACORDER (PCDORDNO , PTPNO , MEMNO , PCDTRIPMEN , PCDORDDAY ,PCDPRICE ,PCDSTATUS, PCDSECPHONE,PCDFAMDATA ,PCDMARK)
                        VALUES('PCD'||LPAD(TO_CHAR(PCD_SEQ.NEXTVAL),6,'0'),'PTP000003','MEM000002',2,TO_DATE('2019-2-4','YYYY-MM-DD')
                        ,23000*2,1,098088899,'王一一 1978-2-2 B123456788','不吃豬肉');
   INSERT INTO PACORDER (PCDORDNO , PTPNO , MEMNO ,  PCDTRIPMEN , PCDORDDAY ,PCDPRICE ,PCDSTATUS, PCDSECPHONE,PCDFAMDATA ,PCDMARK)
                        VALUES('PCD'||LPAD(TO_CHAR(PCD_SEQ.NEXTVAL),6,'0'),'PTP000003','MEM000003',2,TO_DATE('2019-2-4','YYYY-MM-DD')
                        ,23000*2,1,0980187878,'陳二二 1978-2-2 C23365888 王建民 1955-2-2 C223456782','行動不便');
                        
COMMIT;